### ISSUE TITLE
React-navigation嵌套问题

### ISSUE THREAD

**Issue by xiaoxineng** [Murrayee/murray#1]
我使用React-navigation嵌套TabNavigator和StackNavigator，最上层的Tab会一直显示在下面，而我运行你的代码不会，进入二级界面会覆盖Tab，这是为什么。。。

**Comment by Murrayee** [comment]
在其他页面我做了隐藏。还有种方式就是你把tabs的几个页面跟其它页面的做为同级。

**Comment by xiaoxineng** [comment]
写的方法和你的一模一样，但是你说的隐藏我再二级页面里没有看到，比如说Auth下的Setting页面

**Comment by xiaoxineng** [comment]
解决了，看了文档才知道还有一个tabBarVisible属性，谢谢
