### ISSUE TITLE
跑不了了，新手求直接能跑起来的

### ISSUE THREAD

**Issue by nubwang** [Murrayee/murray#2]

**Comment by Murrayee** [comment]
报什么错了

**Comment by nubwang** [comment]
不能打包android,麻烦解决一下，要不然做到最后很尴尬

**Comment by nubwang** [comment]
不能打包android

**Comment by nubwang** [comment]
解决一下呗，要不然做到最后不能打包很尴尬

**Comment by Murrayee** [comment]
安卓我只是在模拟器上跑起来，还没有做适配和调整，打包也没有测试~  我抽时间弄下哈

**Comment by nubwang** [comment]
嗯，谢谢

**Comment by nubwang** [comment]
我发现一个问题，就是这个项目打包以后app打开几次切换下边导航再退出再进入，反复几次就反应越来越慢，最后大概点击以后1.5秒才反应切换，没数据请求，这是怎么了？有时间你看一下......

**Comment by nubwang** [comment]
打包以后在手机上安装，导航切换切换几次，退出再进入，反复几次以后，TabNavigator切换会非常慢，大概得1.5秒才能反应，不是动画卡顿，是根本不反应

**Comment by nubwang** [comment]
在模拟器上是点了就立马切换

**Comment by nubwang** [comment]
大神，要是能达到像模拟器哪样切换的速度就好了，你这个项目有好的优化方法么，新手求解答
