### ISSUE TITLE
yarn install 报错

### ISSUE THREAD

**Issue by shdulu** [murrayee/murray#3]
error An unexpected error occurred: "http://registry.npm.taobao.org/antd-mobile-rn-rn/download/antd-mobile-rn-rn-2.2.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "E:\\testProject\\react-native\\murray-master\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by murrayee** [comment]
重新拉下
