### ISSUE TITLE
页面标题不显示

### ISSUE THREAD

**Issue by debugerlu** [Murrayee/murray#6]
![image](https://user-images.githubusercontent.com/8312011/46258727-0cca6f80-c502-11e8-813a-033f92a400bb.png)
![image](https://user-images.githubusercontent.com/8312011/46258731-24095d00-c502-11e8-8c5f-923ee6f3a39b.png)
配置好了headerTitle标题就是不能显示.

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by murrayee** [comment]
tab页面如果按照上面那种的话，在v2的react-naviagtion里面createButtomTabNavigator这个创建的页面不包括header部分了。你需要把每个tab页单独用createStackNavigator创建，然后放到的createButtomTabNavigator里面就可以了。回头我更新下。
