### ISSUE TITLE
跑不起来，一直报错

### ISSUE THREAD

**Issue by xc233** [Murrayee/murray#7]
`Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\zhang\.gradle\caches\transforms-1\files-1.1\exoplayer-ui-2.9.3.aar\71fbb07614aa923ea795e0441edc9eb6\jars\classes.jar`

大佬能不能帮我看下这是什么问题，非常感谢。

**Comment by murrayee** [comment]
我晚上回去帮你看看哈

**Comment by murrayee** [comment]
@xc233   react-native   link

**Comment by murrayee** [comment]
![image](https://user-images.githubusercontent.com/20828177/53943584-5abe5180-40f8-11e9-8ae4-08a56264dbe4.png)

安卓修复了下  ，好像是版本的问题。
